# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
zh:
  languageCode: zh-Hans
  contentDir: content/zh
  title: 殷聪 - Xscience
  params:
    description: 殷聪 (Xscience) 的主页。
  menu:
    main:
      - name: 个人简介
        url: /
        weight: 10
      - name: 研究成果
        url: publication/
        weight: 11
      - name: 数据产品
        url: project/
        weight: 12
      - name: 会议报告
        url: event/
        weight: 13
      - name: 进展动态
        url: post/
        weight: 20
      - name: 学术履历
        url: experience/
        weight: 30
      # - name: 学生培养
      #   url: teaching/
      #   weight: 40
  # Site header
  params:
    # Site header
    header:
      navbar:
        enable: true
        blox: "navbar"
        fixed_to_top: true
        show_search: true
        show_theme_chooser: true
        logo:
          text: "殷聪"

    # Site footer
    footer:
      copyright:
        notice: '© {year} XScience, {license}.'
        license:
          enable: true
          allow_derivatives: false
          share_alike: true
          allow_commercial: false

    # Localization
    locale:
      date_format: '2006年1月2日'
      time_format: '下午3:04'
